default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#Feel Free to change the username and password to match your local postgres env
development:
  <<: *default
  database: recipess
  username: test2
  password: test2
  port: 5432
  host: localhost

#Feel Free to change the username and password to match your local postgres env
test:
  <<: *default
  database: recipess1
  username: test2
  password: test2
  port: 5432
  host: localhost


production:
  <<: *default
  database: recipess2
  url: <%= ENV['DATABASE_URL'] %>